package com.swtec.sw.persist.model;

import java.io.Serializable;

public class AreaCodeInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sw_area_code_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = -7291382579748842972L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_area_code_info.area_id
     *
     * @mbggenerated
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_area_code_info.area_name
     *
     * @mbggenerated
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_area_code_info.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_area_code_info.short_name
     *
     * @mbggenerated
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_area_code_info.level_type
     *
     * @mbggenerated
     */
    private String levelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_area_code_info.city_code
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_area_code_info.zip_code
     *
     * @mbggenerated
     */
    private String zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_area_code_info.lng
     *
     * @mbggenerated
     */
    private String lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_area_code_info.lat
     *
     * @mbggenerated
     */
    private String lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_area_code_info.pinyin
     *
     * @mbggenerated
     */
    private String pinyin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_area_code_info.area_id
     *
     * @return the value of sw_area_code_info.area_id
     *
     * @mbggenerated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_area_code_info.area_id
     *
     * @param areaId the value for sw_area_code_info.area_id
     *
     * @mbggenerated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_area_code_info.area_name
     *
     * @return the value of sw_area_code_info.area_name
     *
     * @mbggenerated
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_area_code_info.area_name
     *
     * @param areaName the value for sw_area_code_info.area_name
     *
     * @mbggenerated
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_area_code_info.parent_id
     *
     * @return the value of sw_area_code_info.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_area_code_info.parent_id
     *
     * @param parentId the value for sw_area_code_info.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_area_code_info.short_name
     *
     * @return the value of sw_area_code_info.short_name
     *
     * @mbggenerated
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_area_code_info.short_name
     *
     * @param shortName the value for sw_area_code_info.short_name
     *
     * @mbggenerated
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_area_code_info.level_type
     *
     * @return the value of sw_area_code_info.level_type
     *
     * @mbggenerated
     */
    public String getLevelType() {
        return levelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_area_code_info.level_type
     *
     * @param levelType the value for sw_area_code_info.level_type
     *
     * @mbggenerated
     */
    public void setLevelType(String levelType) {
        this.levelType = levelType == null ? null : levelType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_area_code_info.city_code
     *
     * @return the value of sw_area_code_info.city_code
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_area_code_info.city_code
     *
     * @param cityCode the value for sw_area_code_info.city_code
     *
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_area_code_info.zip_code
     *
     * @return the value of sw_area_code_info.zip_code
     *
     * @mbggenerated
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_area_code_info.zip_code
     *
     * @param zipCode the value for sw_area_code_info.zip_code
     *
     * @mbggenerated
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_area_code_info.lng
     *
     * @return the value of sw_area_code_info.lng
     *
     * @mbggenerated
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_area_code_info.lng
     *
     * @param lng the value for sw_area_code_info.lng
     *
     * @mbggenerated
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_area_code_info.lat
     *
     * @return the value of sw_area_code_info.lat
     *
     * @mbggenerated
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_area_code_info.lat
     *
     * @param lat the value for sw_area_code_info.lat
     *
     * @mbggenerated
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_area_code_info.pinyin
     *
     * @return the value of sw_area_code_info.pinyin
     *
     * @mbggenerated
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_area_code_info.pinyin
     *
     * @param pinyin the value for sw_area_code_info.pinyin
     *
     * @mbggenerated
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }
}