package com.swtec.sw.persist.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Bill implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sw_bill
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = -3228302575386013117L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_bill.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_bill.order_number
     *
     * @mbggenerated
     */
    private String orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_bill.total_price
     *
     * @mbggenerated
     */
    private BigDecimal totalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_bill.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_bill.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_bill.create_user_id
     *
     * @mbggenerated
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_bill.examine_time
     *
     * @mbggenerated
     */
    private Date examineTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_bill.examine_user_id
     *
     * @mbggenerated
     */
    private String examineUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_bill.bill_id
     *
     * @mbggenerated
     */
    private Integer billId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_bill.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_bill.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_bill.sc_name
     *
     * @mbggenerated
     */
    private String scName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_bill.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_bill.other_expenses
     *
     * @mbggenerated
     */
    private BigDecimal otherExpenses;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_bill.id
     *
     * @return the value of sw_bill.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_bill.id
     *
     * @param id the value for sw_bill.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_bill.order_number
     *
     * @return the value of sw_bill.order_number
     *
     * @mbggenerated
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_bill.order_number
     *
     * @param orderNumber the value for sw_bill.order_number
     *
     * @mbggenerated
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_bill.total_price
     *
     * @return the value of sw_bill.total_price
     *
     * @mbggenerated
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_bill.total_price
     *
     * @param totalPrice the value for sw_bill.total_price
     *
     * @mbggenerated
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_bill.state
     *
     * @return the value of sw_bill.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_bill.state
     *
     * @param state the value for sw_bill.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_bill.create_time
     *
     * @return the value of sw_bill.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_bill.create_time
     *
     * @param createTime the value for sw_bill.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_bill.create_user_id
     *
     * @return the value of sw_bill.create_user_id
     *
     * @mbggenerated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_bill.create_user_id
     *
     * @param createUserId the value for sw_bill.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_bill.examine_time
     *
     * @return the value of sw_bill.examine_time
     *
     * @mbggenerated
     */
    public Date getExamineTime() {
        return examineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_bill.examine_time
     *
     * @param examineTime the value for sw_bill.examine_time
     *
     * @mbggenerated
     */
    public void setExamineTime(Date examineTime) {
        this.examineTime = examineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_bill.examine_user_id
     *
     * @return the value of sw_bill.examine_user_id
     *
     * @mbggenerated
     */
    public String getExamineUserId() {
        return examineUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_bill.examine_user_id
     *
     * @param examineUserId the value for sw_bill.examine_user_id
     *
     * @mbggenerated
     */
    public void setExamineUserId(String examineUserId) {
        this.examineUserId = examineUserId == null ? null : examineUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_bill.bill_id
     *
     * @return the value of sw_bill.bill_id
     *
     * @mbggenerated
     */
    public Integer getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_bill.bill_id
     *
     * @param billId the value for sw_bill.bill_id
     *
     * @mbggenerated
     */
    public void setBillId(Integer billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_bill.type
     *
     * @return the value of sw_bill.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_bill.type
     *
     * @param type the value for sw_bill.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_bill.name
     *
     * @return the value of sw_bill.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_bill.name
     *
     * @param name the value for sw_bill.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_bill.sc_name
     *
     * @return the value of sw_bill.sc_name
     *
     * @mbggenerated
     */
    public String getScName() {
        return scName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_bill.sc_name
     *
     * @param scName the value for sw_bill.sc_name
     *
     * @mbggenerated
     */
    public void setScName(String scName) {
        this.scName = scName == null ? null : scName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_bill.address
     *
     * @return the value of sw_bill.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_bill.address
     *
     * @param address the value for sw_bill.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_bill.other_expenses
     *
     * @return the value of sw_bill.other_expenses
     *
     * @mbggenerated
     */
    public BigDecimal getOtherExpenses() {
        return otherExpenses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_bill.other_expenses
     *
     * @param otherExpenses the value for sw_bill.other_expenses
     *
     * @mbggenerated
     */
    public void setOtherExpenses(BigDecimal otherExpenses) {
        this.otherExpenses = otherExpenses;
    }
}