package com.swtec.sw.persist.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class CommodityBill implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sw_commodity_bill
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = -3165919419572984296L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity_bill.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity_bill.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity_bill.commodity_id
     *
     * @mbggenerated
     */
    private Integer commodityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity_bill.bill_id
     *
     * @mbggenerated
     */
    private Integer billId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity_bill.commodity_number
     *
     * @mbggenerated
     */
    private Integer commodityNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity_bill.unit_price
     *
     * @mbggenerated
     */
    private BigDecimal unitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity_bill.bill_type
     *
     * @mbggenerated
     */
    private String billType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity_bill.id
     *
     * @return the value of sw_commodity_bill.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity_bill.id
     *
     * @param id the value for sw_commodity_bill.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity_bill.create_time
     *
     * @return the value of sw_commodity_bill.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity_bill.create_time
     *
     * @param createTime the value for sw_commodity_bill.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity_bill.commodity_id
     *
     * @return the value of sw_commodity_bill.commodity_id
     *
     * @mbggenerated
     */
    public Integer getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity_bill.commodity_id
     *
     * @param commodityId the value for sw_commodity_bill.commodity_id
     *
     * @mbggenerated
     */
    public void setCommodityId(Integer commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity_bill.bill_id
     *
     * @return the value of sw_commodity_bill.bill_id
     *
     * @mbggenerated
     */
    public Integer getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity_bill.bill_id
     *
     * @param billId the value for sw_commodity_bill.bill_id
     *
     * @mbggenerated
     */
    public void setBillId(Integer billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity_bill.commodity_number
     *
     * @return the value of sw_commodity_bill.commodity_number
     *
     * @mbggenerated
     */
    public Integer getCommodityNumber() {
        return commodityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity_bill.commodity_number
     *
     * @param commodityNumber the value for sw_commodity_bill.commodity_number
     *
     * @mbggenerated
     */
    public void setCommodityNumber(Integer commodityNumber) {
        this.commodityNumber = commodityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity_bill.unit_price
     *
     * @return the value of sw_commodity_bill.unit_price
     *
     * @mbggenerated
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity_bill.unit_price
     *
     * @param unitPrice the value for sw_commodity_bill.unit_price
     *
     * @mbggenerated
     */
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity_bill.bill_type
     *
     * @return the value of sw_commodity_bill.bill_type
     *
     * @mbggenerated
     */
    public String getBillType() {
        return billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity_bill.bill_type
     *
     * @param billType the value for sw_commodity_bill.bill_type
     *
     * @mbggenerated
     */
    public void setBillType(String billType) {
        this.billType = billType == null ? null : billType.trim();
    }
}