package com.swtec.sw.persist.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Commodity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sw_commodity
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = -6092603730750443919L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity.brand
     *
     * @mbggenerated
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity.commodity_category_id
     *
     * @mbggenerated
     */
    private Integer commodityCategoryId;
    
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity.warehouse_type
     *
     * @mbggenerated
     */
    private String warehouseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity.bar_code
     *
     * @mbggenerated
     */
    private Integer barCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity.commodity_identifier
     *
     * @mbggenerated
     */
    private String commodityIdentifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity.commodity_name
     *
     * @mbggenerated
     */
    private String commodityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity.model
     *
     * @mbggenerated
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity.selling_price
     *
     * @mbggenerated
     */
    private BigDecimal sellingPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity.wholesale_price
     *
     * @mbggenerated
     */
    private BigDecimal wholesalePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity.cost_price
     *
     * @mbggenerated
     */
    private BigDecimal costPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity.company_type
     *
     * @mbggenerated
     */
    private String companyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity.supplier_id
     *
     * @mbggenerated
     */
    private Integer supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity.upper_limit_number
     *
     * @mbggenerated
     */
    private Integer upperLimitNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity.lower_number
     *
     * @mbggenerated
     */
    private Integer lowerNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity.commodity_number
     *
     * @mbggenerated
     */
    private Integer commodityNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity.last_update_time
     *
     * @mbggenerated
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity.user_update_id
     *
     * @mbggenerated
     */
    private Integer userUpdateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_commodity.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity.id
     *
     * @return the value of sw_commodity.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }
    
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity.warehouse_type
     *
     * @param warehouseType the value for sw_commodity.warehouse_type
     *
     * @mbggenerated
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity.id
     *
     * @param id the value for sw_commodity.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity.brand
     *
     * @return the value of sw_commodity.brand
     *
     * @mbggenerated
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity.brand
     *
     * @param brand the value for sw_commodity.brand
     *
     * @mbggenerated
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity.commodity_category_id
     *
     * @return the value of sw_commodity.commodity_category_id
     *
     * @mbggenerated
     */
    public Integer getCommodityCategoryId() {
        return commodityCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity.commodity_category_id
     *
     * @param commodityCategoryId the value for sw_commodity.commodity_category_id
     *
     * @mbggenerated
     */
    public void setCommodityCategoryId(Integer commodityCategoryId) {
        this.commodityCategoryId = commodityCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity.warehouse_type
     *
     * @return the value of sw_commodity.warehouse_type
     *
     * @mbggenerated
     */
    public String getWarehouseType() {
        return warehouseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity.warehouse_type
     *
     * @param warehouseType the value for sw_commodity.warehouse_type
     *
     * @mbggenerated
     */
    public void setWarehouseType(String warehouseType) {
        this.warehouseType = warehouseType == null ? null : warehouseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity.bar_code
     *
     * @return the value of sw_commodity.bar_code
     *
     * @mbggenerated
     */
    public Integer getBarCode() {
        return barCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity.bar_code
     *
     * @param barCode the value for sw_commodity.bar_code
     *
     * @mbggenerated
     */
    public void setBarCode(Integer barCode) {
        this.barCode = barCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity.commodity_identifier
     *
     * @return the value of sw_commodity.commodity_identifier
     *
     * @mbggenerated
     */
    public String getCommodityIdentifier() {
        return commodityIdentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity.commodity_identifier
     *
     * @param commodityIdentifier the value for sw_commodity.commodity_identifier
     *
     * @mbggenerated
     */
    public void setCommodityIdentifier(String commodityIdentifier) {
        this.commodityIdentifier = commodityIdentifier == null ? null : commodityIdentifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity.commodity_name
     *
     * @return the value of sw_commodity.commodity_name
     *
     * @mbggenerated
     */
    public String getCommodityName() {
        return commodityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity.commodity_name
     *
     * @param commodityName the value for sw_commodity.commodity_name
     *
     * @mbggenerated
     */
    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName == null ? null : commodityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity.model
     *
     * @return the value of sw_commodity.model
     *
     * @mbggenerated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity.model
     *
     * @param model the value for sw_commodity.model
     *
     * @mbggenerated
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity.selling_price
     *
     * @return the value of sw_commodity.selling_price
     *
     * @mbggenerated
     */
    public BigDecimal getSellingPrice() {
        return sellingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity.selling_price
     *
     * @param sellingPrice the value for sw_commodity.selling_price
     *
     * @mbggenerated
     */
    public void setSellingPrice(BigDecimal sellingPrice) {
        this.sellingPrice = sellingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity.wholesale_price
     *
     * @return the value of sw_commodity.wholesale_price
     *
     * @mbggenerated
     */
    public BigDecimal getWholesalePrice() {
        return wholesalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity.wholesale_price
     *
     * @param wholesalePrice the value for sw_commodity.wholesale_price
     *
     * @mbggenerated
     */
    public void setWholesalePrice(BigDecimal wholesalePrice) {
        this.wholesalePrice = wholesalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity.cost_price
     *
     * @return the value of sw_commodity.cost_price
     *
     * @mbggenerated
     */
    public BigDecimal getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity.cost_price
     *
     * @param costPrice the value for sw_commodity.cost_price
     *
     * @mbggenerated
     */
    public void setCostPrice(BigDecimal costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity.company_type
     *
     * @return the value of sw_commodity.company_type
     *
     * @mbggenerated
     */
    public String getCompanyType() {
        return companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity.company_type
     *
     * @param companyType the value for sw_commodity.company_type
     *
     * @mbggenerated
     */
    public void setCompanyType(String companyType) {
        this.companyType = companyType == null ? null : companyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity.supplier_id
     *
     * @return the value of sw_commodity.supplier_id
     *
     * @mbggenerated
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity.supplier_id
     *
     * @param supplierId the value for sw_commodity.supplier_id
     *
     * @mbggenerated
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity.upper_limit_number
     *
     * @return the value of sw_commodity.upper_limit_number
     *
     * @mbggenerated
     */
    public Integer getUpperLimitNumber() {
        return upperLimitNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity.upper_limit_number
     *
     * @param upperLimitNumber the value for sw_commodity.upper_limit_number
     *
     * @mbggenerated
     */
    public void setUpperLimitNumber(Integer upperLimitNumber) {
        this.upperLimitNumber = upperLimitNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity.lower_number
     *
     * @return the value of sw_commodity.lower_number
     *
     * @mbggenerated
     */
    public Integer getLowerNumber() {
        return lowerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity.lower_number
     *
     * @param lowerNumber the value for sw_commodity.lower_number
     *
     * @mbggenerated
     */
    public void setLowerNumber(Integer lowerNumber) {
        this.lowerNumber = lowerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity.commodity_number
     *
     * @return the value of sw_commodity.commodity_number
     *
     * @mbggenerated
     */
    public Integer getCommodityNumber() {
        return commodityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity.commodity_number
     *
     * @param commodityNumber the value for sw_commodity.commodity_number
     *
     * @mbggenerated
     */
    public void setCommodityNumber(Integer commodityNumber) {
        this.commodityNumber = commodityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity.create_time
     *
     * @return the value of sw_commodity.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity.create_time
     *
     * @param createTime the value for sw_commodity.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity.user_id
     *
     * @return the value of sw_commodity.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity.user_id
     *
     * @param userId the value for sw_commodity.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity.last_update_time
     *
     * @return the value of sw_commodity.last_update_time
     *
     * @mbggenerated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity.last_update_time
     *
     * @param lastUpdateTime the value for sw_commodity.last_update_time
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity.user_update_id
     *
     * @return the value of sw_commodity.user_update_id
     *
     * @mbggenerated
     */
    public Integer getUserUpdateId() {
        return userUpdateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity.user_update_id
     *
     * @param userUpdateId the value for sw_commodity.user_update_id
     *
     * @mbggenerated
     */
    public void setUserUpdateId(Integer userUpdateId) {
        this.userUpdateId = userUpdateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_commodity.remarks
     *
     * @return the value of sw_commodity.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_commodity.remarks
     *
     * @param remarks the value for sw_commodity.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}