package com.swtec.sw.persist.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class MtOrder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sw_mt_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 6961577006936314411L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_mt_order.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_mt_order.order_id
     *
     * @mbggenerated
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_mt_order.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_mt_order.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_mt_order.bug_detail
     *
     * @mbggenerated
     */
    private String bugDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_mt_order.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_mt_order.total_price
     *
     * @mbggenerated
     */
    private BigDecimal totalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_mt_order.bugs
     *
     * @mbggenerated
     */
    private String bugs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_mt_order.machine_bug_ids
     *
     * @mbggenerated
     */
    private String machineBugIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_mt_order.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_mt_order.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_mt_order.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_mt_order.id
     *
     * @return the value of sw_mt_order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_mt_order.id
     *
     * @param id the value for sw_mt_order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_mt_order.order_id
     *
     * @return the value of sw_mt_order.order_id
     *
     * @mbggenerated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_mt_order.order_id
     *
     * @param orderId the value for sw_mt_order.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_mt_order.real_name
     *
     * @return the value of sw_mt_order.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_mt_order.real_name
     *
     * @param realName the value for sw_mt_order.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_mt_order.mobile
     *
     * @return the value of sw_mt_order.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_mt_order.mobile
     *
     * @param mobile the value for sw_mt_order.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_mt_order.bug_detail
     *
     * @return the value of sw_mt_order.bug_detail
     *
     * @mbggenerated
     */
    public String getBugDetail() {
        return bugDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_mt_order.bug_detail
     *
     * @param bugDetail the value for sw_mt_order.bug_detail
     *
     * @mbggenerated
     */
    public void setBugDetail(String bugDetail) {
        this.bugDetail = bugDetail == null ? null : bugDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_mt_order.address
     *
     * @return the value of sw_mt_order.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_mt_order.address
     *
     * @param address the value for sw_mt_order.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_mt_order.total_price
     *
     * @return the value of sw_mt_order.total_price
     *
     * @mbggenerated
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_mt_order.total_price
     *
     * @param totalPrice the value for sw_mt_order.total_price
     *
     * @mbggenerated
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_mt_order.bugs
     *
     * @return the value of sw_mt_order.bugs
     *
     * @mbggenerated
     */
    public String getBugs() {
        return bugs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_mt_order.bugs
     *
     * @param bugs the value for sw_mt_order.bugs
     *
     * @mbggenerated
     */
    public void setBugs(String bugs) {
        this.bugs = bugs == null ? null : bugs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_mt_order.machine_bug_ids
     *
     * @return the value of sw_mt_order.machine_bug_ids
     *
     * @mbggenerated
     */
    public String getMachineBugIds() {
        return machineBugIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_mt_order.machine_bug_ids
     *
     * @param machineBugIds the value for sw_mt_order.machine_bug_ids
     *
     * @mbggenerated
     */
    public void setMachineBugIds(String machineBugIds) {
        this.machineBugIds = machineBugIds == null ? null : machineBugIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_mt_order.description
     *
     * @return the value of sw_mt_order.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_mt_order.description
     *
     * @param description the value for sw_mt_order.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_mt_order.create_time
     *
     * @return the value of sw_mt_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_mt_order.create_time
     *
     * @param createTime the value for sw_mt_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_mt_order.update_time
     *
     * @return the value of sw_mt_order.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_mt_order.update_time
     *
     * @param updateTime the value for sw_mt_order.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}