package com.swtec.sw.persist.model;

import com.swtec.sw.persist.enums.MenuType;
import com.swtec.sw.persist.enums.ShowType;
import java.io.Serializable;
import java.util.Date;

public class Resource implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sw_resource
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = -5552041544209959862L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_resource.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_resource.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_resource.resource_desc
     *
     * @mbggenerated
     */
    private String resourceDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_resource.is_show
     *
     * @mbggenerated
     */
    private ShowType isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_resource.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_resource.weight
     *
     * @mbggenerated
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_resource.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_resource.parent_ids
     *
     * @mbggenerated
     */
    private String parentIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_resource.permission
     *
     * @mbggenerated
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_resource.menu_type
     *
     * @mbggenerated
     */
    private MenuType menuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_resource.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_resource.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_resource.id
     *
     * @return the value of sw_resource.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_resource.id
     *
     * @param id the value for sw_resource.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_resource.name
     *
     * @return the value of sw_resource.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_resource.name
     *
     * @param name the value for sw_resource.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_resource.resource_desc
     *
     * @return the value of sw_resource.resource_desc
     *
     * @mbggenerated
     */
    public String getResourceDesc() {
        return resourceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_resource.resource_desc
     *
     * @param resourceDesc the value for sw_resource.resource_desc
     *
     * @mbggenerated
     */
    public void setResourceDesc(String resourceDesc) {
        this.resourceDesc = resourceDesc == null ? null : resourceDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_resource.is_show
     *
     * @return the value of sw_resource.is_show
     *
     * @mbggenerated
     */
    public ShowType getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_resource.is_show
     *
     * @param isShow the value for sw_resource.is_show
     *
     * @mbggenerated
     */
    public void setIsShow(ShowType isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_resource.url
     *
     * @return the value of sw_resource.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_resource.url
     *
     * @param url the value for sw_resource.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_resource.weight
     *
     * @return the value of sw_resource.weight
     *
     * @mbggenerated
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_resource.weight
     *
     * @param weight the value for sw_resource.weight
     *
     * @mbggenerated
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_resource.parent_id
     *
     * @return the value of sw_resource.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_resource.parent_id
     *
     * @param parentId the value for sw_resource.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_resource.parent_ids
     *
     * @return the value of sw_resource.parent_ids
     *
     * @mbggenerated
     */
    public String getParentIds() {
        return parentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_resource.parent_ids
     *
     * @param parentIds the value for sw_resource.parent_ids
     *
     * @mbggenerated
     */
    public void setParentIds(String parentIds) {
        this.parentIds = parentIds == null ? null : parentIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_resource.permission
     *
     * @return the value of sw_resource.permission
     *
     * @mbggenerated
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_resource.permission
     *
     * @param permission the value for sw_resource.permission
     *
     * @mbggenerated
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_resource.menu_type
     *
     * @return the value of sw_resource.menu_type
     *
     * @mbggenerated
     */
    public MenuType getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_resource.menu_type
     *
     * @param menuType the value for sw_resource.menu_type
     *
     * @mbggenerated
     */
    public void setMenuType(MenuType menuType) {
        this.menuType = menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_resource.create_time
     *
     * @return the value of sw_resource.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_resource.create_time
     *
     * @param createTime the value for sw_resource.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_resource.update_time
     *
     * @return the value of sw_resource.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_resource.update_time
     *
     * @param updateTime the value for sw_resource.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}