package com.swtec.sw.persist.model;

import java.io.Serializable;
import java.util.Date;

public class Supplier implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sw_supplier
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = -5552041502582527480L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_supplier.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_supplier.supplier_name
     *
     * @mbggenerated
     */
    private String supplierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_supplier.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_supplier.telephone
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_supplier.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_supplier.supplier_commodity
     *
     * @mbggenerated
     */
    private String supplierCommodity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_supplier.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_supplier.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_supplier.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sw_supplier.company_name
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_supplier.id
     *
     * @return the value of sw_supplier.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_supplier.id
     *
     * @param id the value for sw_supplier.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_supplier.supplier_name
     *
     * @return the value of sw_supplier.supplier_name
     *
     * @mbggenerated
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_supplier.supplier_name
     *
     * @param supplierName the value for sw_supplier.supplier_name
     *
     * @mbggenerated
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName == null ? null : supplierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_supplier.phone
     *
     * @return the value of sw_supplier.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_supplier.phone
     *
     * @param phone the value for sw_supplier.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_supplier.telephone
     *
     * @return the value of sw_supplier.telephone
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_supplier.telephone
     *
     * @param telephone the value for sw_supplier.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_supplier.email
     *
     * @return the value of sw_supplier.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_supplier.email
     *
     * @param email the value for sw_supplier.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_supplier.supplier_commodity
     *
     * @return the value of sw_supplier.supplier_commodity
     *
     * @mbggenerated
     */
    public String getSupplierCommodity() {
        return supplierCommodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_supplier.supplier_commodity
     *
     * @param supplierCommodity the value for sw_supplier.supplier_commodity
     *
     * @mbggenerated
     */
    public void setSupplierCommodity(String supplierCommodity) {
        this.supplierCommodity = supplierCommodity == null ? null : supplierCommodity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_supplier.name
     *
     * @return the value of sw_supplier.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_supplier.name
     *
     * @param name the value for sw_supplier.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_supplier.create_time
     *
     * @return the value of sw_supplier.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_supplier.create_time
     *
     * @param createTime the value for sw_supplier.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_supplier.remarks
     *
     * @return the value of sw_supplier.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_supplier.remarks
     *
     * @param remarks the value for sw_supplier.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sw_supplier.company_name
     *
     * @return the value of sw_supplier.company_name
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sw_supplier.company_name
     *
     * @param companyName the value for sw_supplier.company_name
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }
}