package com.swtec.sw.persist.mapper;

import com.swtec.sw.persist.model.CommodityBill;
import com.swtec.sw.persist.model.CommodityBillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommodityBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_commodity_bill
     *
     * @mbggenerated
     */
    int countByExample(CommodityBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_commodity_bill
     *
     * @mbggenerated
     */
    int deleteByExample(CommodityBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_commodity_bill
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_commodity_bill
     *
     * @mbggenerated
     */
    int insert(CommodityBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_commodity_bill
     *
     * @mbggenerated
     */
    int insertSelective(CommodityBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_commodity_bill
     *
     * @mbggenerated
     */
    List<CommodityBill> selectByExample(CommodityBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_commodity_bill
     *
     * @mbggenerated
     */
    CommodityBill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_commodity_bill
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CommodityBill record, @Param("example") CommodityBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_commodity_bill
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CommodityBill record, @Param("example") CommodityBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_commodity_bill
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CommodityBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_commodity_bill
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommodityBill record);
}