package com.swtec.sw.persist.mapper;

import com.swtec.sw.persist.model.MtMachineBug;
import com.swtec.sw.persist.model.MtMachineBugExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MtMachineBugMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_mt_machine_bug
     *
     * @mbggenerated
     */
    int countByExample(MtMachineBugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_mt_machine_bug
     *
     * @mbggenerated
     */
    int deleteByExample(MtMachineBugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_mt_machine_bug
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_mt_machine_bug
     *
     * @mbggenerated
     */
    int insert(MtMachineBug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_mt_machine_bug
     *
     * @mbggenerated
     */
    int insertSelective(MtMachineBug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_mt_machine_bug
     *
     * @mbggenerated
     */
    List<MtMachineBug> selectByExample(MtMachineBugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_mt_machine_bug
     *
     * @mbggenerated
     */
    MtMachineBug selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_mt_machine_bug
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MtMachineBug record, @Param("example") MtMachineBugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_mt_machine_bug
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MtMachineBug record, @Param("example") MtMachineBugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_mt_machine_bug
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MtMachineBug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_mt_machine_bug
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MtMachineBug record);
}