package com.swtec.sw.persist.mapper;

import com.swtec.sw.persist.model.MtTemplate;
import com.swtec.sw.persist.model.MtTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MtTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_mt_template
     *
     * @mbggenerated
     */
    int countByExample(MtTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_mt_template
     *
     * @mbggenerated
     */
    int deleteByExample(MtTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_mt_template
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_mt_template
     *
     * @mbggenerated
     */
    int insert(MtTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_mt_template
     *
     * @mbggenerated
     */
    int insertSelective(MtTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_mt_template
     *
     * @mbggenerated
     */
    List<MtTemplate> selectByExampleWithBLOBs(MtTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_mt_template
     *
     * @mbggenerated
     */
    List<MtTemplate> selectByExample(MtTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_mt_template
     *
     * @mbggenerated
     */
    MtTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_mt_template
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MtTemplate record, @Param("example") MtTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_mt_template
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") MtTemplate record, @Param("example") MtTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_mt_template
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MtTemplate record, @Param("example") MtTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_mt_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MtTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_mt_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(MtTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_mt_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MtTemplate record);
}