package com.swtec.sw.persist.mapper;

import com.swtec.sw.persist.model.ResourceRole;
import com.swtec.sw.persist.model.ResourceRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResourceRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_resource_role
     *
     * @mbggenerated
     */
    int countByExample(ResourceRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_resource_role
     *
     * @mbggenerated
     */
    int deleteByExample(ResourceRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_resource_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_resource_role
     *
     * @mbggenerated
     */
    int insert(ResourceRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_resource_role
     *
     * @mbggenerated
     */
    int insertSelective(ResourceRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_resource_role
     *
     * @mbggenerated
     */
    List<ResourceRole> selectByExample(ResourceRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_resource_role
     *
     * @mbggenerated
     */
    ResourceRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_resource_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ResourceRole record, @Param("example") ResourceRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_resource_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ResourceRole record, @Param("example") ResourceRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_resource_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ResourceRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sw_resource_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ResourceRole record);
}